---

- name: Create pool
  hosts: lb
  connection: local
  
  tasks:
    - name: create app1 server pool
      bigip_pool:
        name: app1_p1
        monitors: "/Common/http"
        lb_method: round-robin
        server: 192.168.90.200
        user: admin
        password: W3lcome098!
        validate_certs: no
      delegate_to: localhost
